<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="7.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eShop.UseCases\eShop.UseCases.csproj" />
    <ProjectReference Include="..\..\e_Shop.CoreBusiness\e_Shop.CoreBusiness.csproj" />
    <ProjectReference Include="..\eShop.Web.Common\eShop.Web.Common.csproj" />
  </ItemGroup>

</Project>
