<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ReferencePath>C:\Program Files (x86)\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Common\SAP BusinessObjects Enterprise XI 4.0\win64_x64\dotnet\</ReferencePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eShop.UseCases\eShop.UseCases.csproj" />
    <ProjectReference Include="..\..\e_Shop.CoreBusiness\e_Shop.CoreBusiness.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{c0c07587-41a7-46c8-8fbd-3f9c8ebe2ddc}" />
  </ItemGroup>

</Project>
